var shoppinglist = [["milk", 3], ["eggs", 10], ["Banas", 12]];
shoppinglist.push(["tomato", 5], ["potato", 7]);
shoppinglist.pop();
shoppinglist.shift();
shoppinglist.unshift(["cabbage", 6]);
var listarray = shoppinglist[3][0];
console.log(shoppinglist);
var sumarray = shoppinglist[0][1] + shoppinglist[1][1];
console.log("sum of first two items:", sumarray);
console.log("First element of 3rd list is:", listarray);
